const hre = require("hardhat");

async function checkInteractions() {
  const contractAddress = "0x5FbDB2315678afecb367f032d93F642f64180aa3"; // Replace with your deployed contract address
  const contract = await hre.ethers.getContractAt("PeerReview", contractAddress);
  
  // Retrieve accounts generated by Hardhat
  const accounts = await hre.ethers.getSigners();

  for (let i = 0; i < 50; i++) {
    const user = accounts[i];
    // Call the custom getter function to get interactions
    const interactions = await contract.getUserInteractions(user.address);

    console.log(`\nUser ${i + 1} (${user.address}) Interactions:`);

    // Loop through each interaction entry for the user
    for (let j = 0; j < interactions.length; j++) {
      const interaction = interactions[j];
      console.log(`  Interaction ${j + 1}:`);
      console.log(`    Target User: ${interaction.user}`);
      console.log(`    Honesty: ${interaction.honesty}`);
    }
  }
}

checkInteractions()
  .then(() => console.log("Interaction check complete!"))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
