const hre = require("hardhat");

async function main() {
  // Specify the contract address
  const contractAddress = "0x5FbDB2315678afecb367f032d93F642f64180aa3"; // Replace with the deployed contract address

  // Retrieve the contract ABI
  const contract = await hre.ethers.getContractAt("PeerReview", contractAddress);

  // Retrieve accounts generated by Hardhat
  const accounts = await hre.ethers.getSigners();

  // Register 50 users with the contract
  for (let i = 0; i < 50; i++) {
    const user = accounts[i];

    // Connect to the contract as each user and call registerUser
    const tx = await contract.connect(user).registerUser(["testTag" + i]);
    await tx.wait();
    console.log(`Registered user ${i + 1}: ${user.address}`);
  }

  console.log("50 users registered successfully!");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
